language: node_js
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  - JWT_SECRET=test-secret
cache:
  yarn: true
services:
  - mongodb
install:
  - yarn install

script:
  - yarn test
